//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrder
    {
        public int IOLink { get; set; }
        public int IO_StockLink { get; set; }
        public System.Guid IO_RefNo { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string ItemOrderNote { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> ExclAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> InclAmount { get; set; }
    
        public virtual StkItem StkItem { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
